### ISSUE TITLE
typo and check corrections

### ISSUE THREAD

**Issue by mcerveny** [gfto/libtsfuncs#2]
There is some little patch:
```
diff --git a/crc.c b/crc.c
index 6f9af50..3b86af1 100644
--- a/crc.c
+++ b/crc.c
@@ -46,7 +46,7 @@ uint32_t ts_crc32(uint8_t *data, int data_size) {
        return crc;
 }
 
-u_int32_t ts_crc32_section(struct ts_section_header *section_header) {
+uint32_t ts_crc32_section(struct ts_section_header *section_header) {
        return ts_crc32(section_header->section_data, section_header->section_data_len);
 }
 
diff --git a/tsfuncs.c b/tsfuncs.c
index 6d78479..84b94cf 100644
--- a/tsfuncs.c
+++ b/tsfuncs.c
@@ -265,7 +265,7 @@ uint8_t *ts_packet_header_parse(uint8_t *ts_packet, struct ts_header *ts_header)
        if (!ts_header->payload_field && ts_header->adapt_len > 183)
                goto return_error;
 
-       if (ts_header->payload_offset > TS_MAX_PAYLOAD_SIZE) // Validity check
+       if (ts_header->payload_offset > TS_PACKET_SIZE) // Validity check
                goto return_error;
 
        ts_header->payload_size = TS_PACKET_SIZE - ts_header->payload_offset;
```

**Comment by lars18th** [comment]
Hi,

First part of the patch is already done in the last commit https://github.com/gfto/libtsfuncs/commit/f2456cb2f4a040d7218e5fa7f6bedaf11e4eab81

Regarding the second part:
- **TS_PACKET_SIZE** = Size of a TS packet (188).
- **TS_MAX_PAYLOAD_SIZE** = 188 - 4 (4 is the minimum size of the TS Header, so MaxPayload is this).
- **ts_header->payload_offset** = Index of the start of the payload. See:
https://github.com/gfto/libtsfuncs/blob/45e7e999a17c1954915295bd13b242bbd937cf28/pat_desc.c#L29

So, what is the MAX of the `payload_offset`? The correct answer is the max size of the packet. Because it starts from the start of the packet, and not from the end of the header.

Then I feel the patch is correct: `if (ts_header->payload_offset > TS_PACKET_SIZE) // Validity check`
You agree?

**Comment by mcerveny** [comment]
Both patches equals to my findings - https://github.com/gfto/libtsfuncs/commit/848acf5a92b7ff885466f69c0d4e119f029fc9d6 and https://github.com/gfto/libtsfuncs/pull/6/commits/6fb0de0bb79393c87f20d7578c64e8ae2713dcda .

**Comment by lars18th** [comment]
Hi @mcerveny ,

> Both patches equals to my findings - 848acf5 and 6fb0de0 .

I'm only doing some up-to-date of this project. :smile: 

The first patch is already merged.
The second one, it's waiting in a PR.
My intention is comment about your suggestions, merge the code, and close the issue.

In my opinion, for the next time I feel it's best if you craete a PR.
Regards.

**Comment by gfto** [comment]
I've merged the pull requests so this should be fixed now.
